title: Page

pages:
  template: default

files:
  type: all


fields:
  title:
    label: Title
    type: text
    width: 1/1

  text:
    label: Text
    type: textarea
    size: large
    spellcheck: true
